### ISSUE TITLE
Fabric 1.20.1 crashing with Better Statistics Screen

### ISSUE THREAD

**Issue by SettingDust** [MehVahdJukaar/polytone#15]
https://github.com/TheCSMods/mc-tcdcommons/blob/main/tcdcommons-3-fabric-1.20.1/src/main/java/io/github/thecsdev/tcdcommons/api/client/gui/screen/TScreenWrapper.java#L72

The title isn't gettable when constructing

```
java.lang.ExceptionInInitializerError
	at io.github.thecsdev.betterstats.client.network.BetterStatsClientNetworkHandler.c2s_liveStats(BetterStatsClientNetworkHandler.java:77)
	at io.github.thecsdev.betterstats.client.network.BetterStatsClientNetworkHandler.lambda$static$2(BetterStatsClientNetworkHandler.java:65)
	at MC//net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor.java:156)
	at MC//net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor.java:23)
	at MC//net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor.java:130)
	at MC//net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor.java:115)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1175)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at app//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at app//org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at app//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NullPointerException: Cannot invoke "io.github.thecsdev.tcdcommons.api.client.gui.screen.TScreen.getTitle()" because "this.target" is null
	at io.github.thecsdev.tcdcommons.api.client.gui.screen.TScreenWrapper.getTitle(TScreenWrapper.java:72)
	at net.mehvahdjukaar.polytone.slotify.GuiModifierManager.getGuiModifier(GuiModifierManager.java:171)
	at MC//net.minecraft.client.gui.screen.Screen.handler$mgi009$polytone$onInit(Screen.java:14171)
	at MC//net.minecraft.client.gui.screen.Screen.<init>(Screen.java:99)
	at io.github.thecsdev.tcdcommons.api.client.gui.screen.TScreenWrapper.<init>(TScreenWrapper.java:62)
	at io.github.thecsdev.betterstats.client.gui.screen.hud.BetterStatsHudScreenWrapper.<init>(BetterStatsHudScreenWrapper.java:11)
	at io.github.thecsdev.betterstats.client.gui.screen.hud.BetterStatsHudScreen.createScreenWrapper(BetterStatsHudScreen.java:46)
	at io.github.thecsdev.tcdcommons.api.client.gui.screen.TScreen.<init>(TScreen.java:54)
	at io.github.thecsdev.tcdcommons.api.client.gui.screen.TWidgetHudScreen.<init>(TWidgetHudScreen.java:41)
	at io.github.thecsdev.betterstats.client.gui.screen.hud.BetterStatsHudScreen.<init>(BetterStatsHudScreen.java:44)
	at io.github.thecsdev.betterstats.client.gui.screen.hud.BetterStatsHudScreen.<clinit>(BetterStatsHudScreen.java:37)
	... 15 more
```

**Comment by MehVahdJukaar** [comment]
oh yeah. just recently changed that code. Gues that's why i had it differnetly. Ill revert
