### ISSUE TITLE
Crash with Polytone and New Default+

### ISSUE THREAD

**Issue by Madis0** [MehVahdJukaar/polytone#44]
Polytone 1.20.6-1.18.8
New Default+ v1.74

Crashes upon world load; also tested with Sodium+Indium with same result

```
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-05-19 18:27:34
Description: Tessellating block in world - Indigo Renderer

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_5455.method_33310(net.minecraft.class_5321)" because the return value of "java.lang.ref.WeakReference.get()" is null
	at net.mehvahdjukaar.polytone.colormap.IColormapNumberProvider.lambda$static$1(IColormapNumberProvider.java:114)
	at net.mehvahdjukaar.polytone.colormap.Colormap.sampleColor(Colormap.java:163)
	at net.mehvahdjukaar.polytone.colormap.Colormap.calculateBlendedColor(Colormap.java:194)
	at net.minecraft.class_638.md152632$polytone$lambda$fixVanillaColorCache$0$3(class_638.java:2619)
	at net.minecraft.class_4700.method_23770(class_4700.java:101)
	at net.minecraft.class_638.method_23752(class_638.java:785)
	at net.minecraft.class_853.method_23752(class_853.java:67)
	at net.mehvahdjukaar.polytone.colormap.Colormap.getColor(Colormap.java:156)
	at net.minecraft.class_324.method_1697(class_324.java:121)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.blockColor(BlockRenderInfo.java:101)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext.colorizeQuad(AbstractBlockRenderContext.java:135)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:127)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext$2.emitDirectly(AbstractBlockRenderContext.java:69)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:220)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56)
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:65)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1041)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$zji000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:769)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:565)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:477)
	at net.minecraft.class_846.method_22757(class_846.java:111)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.mehvahdjukaar.polytone.colormap.IColormapNumberProvider.lambda$static$1(IColormapNumberProvider.java:114)
	at net.mehvahdjukaar.polytone.colormap.Colormap.sampleColor(Colormap.java:163)
	at net.mehvahdjukaar.polytone.colormap.Colormap.calculateBlendedColor(Colormap.java:194)
	at net.minecraft.class_638.md152632$polytone$lambda$fixVanillaColorCache$0$3(class_638.java:2619)
	at net.minecraft.class_4700.method_23770(class_4700.java:101)
	at net.minecraft.class_638.method_23752(class_638.java:785)
	at net.minecraft.class_853.method_23752(class_853.java:67)
	at net.mehvahdjukaar.polytone.colormap.Colormap.getColor(Colormap.java:156)
	at net.minecraft.class_324.method_1697(class_324.java:121)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.BlockRenderInfo.blockColor(BlockRenderInfo.java:101)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext.colorizeQuad(AbstractBlockRenderContext.java:135)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:127)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.AbstractBlockRenderContext$2.emitDirectly(AbstractBlockRenderContext.java:69)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:220)
	at net.fabricmc.fabric.impl.client.indigo.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56)
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:65)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1041)
	at net.minecraft.class_1097.emitBlockQuads(class_1097.java:574)
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)

-- Block being tessellated --
Details:
	Block: Block{minecraft:grass_block}[snowy=false]
	Block location: World: (-17,92,-96), Section: (at 15,12,0 in -2,5,-6; chunk contains blocks -32,-64,-96 to -17,319,-81), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
Stacktrace:
	at net.fabricmc.fabric.impl.client.indigo.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:98)
	at net.minecraft.class_846$class_851$class_4578.redirect$zji000$fabric-renderer-indigo$hookChunkBuildTessellate(class_846.java:769)
	at net.minecraft.class_846$class_851$class_4578.method_22785(class_846.java:565)
	at net.minecraft.class_846$class_851$class_4578.method_22783(class_846.java:477)
	at net.minecraft.class_846.method_22757(class_846.java:111)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

-- Uptime --
Details:
	JVM uptime: 80.111s
	Wall uptime: 56.911s
	High-res time: 54.810s
	Client ticks: 499 ticks / 24.950s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2548)
	at net.minecraft.class_310.method_43589(class_310.java:965)
	at net.minecraft.class_310.method_54579(class_310.java:978)
	at net.minecraft.class_310.method_1514(class_310.java:879)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)

-- Affected level --
Details:
	All players: 1 total; [class_746['robotkoer'/50, l='ClientLevel', x=-25.50, y=97.00, z=-85.50]]
	Chunk stats: 961, 26
	Level dimension: minecraft:overworld
	Level spawn location: World: (-32,97,-80), Section: (at 0,1,0 in -2,6,-5; chunk contains blocks -32,-64,-80 to -17,319,-65), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 90 game time, 90 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
	Tracked entity count: 42

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, polytone, file/NewDefault+v1.74[MC1.20-1.20.4].zip

-- System Details --
Details:
	Minecraft Version: 1.20.6
	Minecraft Version ID: 1.20.6
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.2, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 990244304 bytes (944 MiB) / 1463812096 bytes (1396 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Plus Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 27.20.100.8783
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20578.11
	Virtual memory used (MB): 12612.75
	Swap memory total (MB): 12610.12
	Swap memory used (MB): 1126.62
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		fabric-api: Fabric API 0.98.0+1.20.6
			fabric-api-base: Fabric API Base 0.4.40+80f8cf51b0
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.59+e9d2a72bb0
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.25+be5d88beb0
			fabric-block-api-v1: Fabric Block API (v1) 1.0.20+6dfe4c9bb0
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.8+80f8cf51b0
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.50+80f8cf51b0
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.12+7f945d5bb0
			fabric-command-api-v1: Fabric Command API (v1) 1.2.45+f71b366fb0
			fabric-command-api-v2: Fabric Command API (v2) 2.2.24+80f8cf51b0
			fabric-commands-v0: Fabric Commands (v0) 0.2.62+df3654b3b0
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.5+b82b2392b0
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.4+7f945d5bb0
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.1.0+70fd1b46b0
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.27+80f8cf51b0
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.16+2a2c66b6b0
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 19.1.0+ad474493b0
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.68+94793913b0
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.8+e9d2a72bb0
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.6+c5fc38b3b0
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.50+80f8cf51b0
			fabric-item-api-v1: Fabric Item API (v1) 8.2.0+5bcea88ab0
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.39+aae0949ab0
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.45+80f8cf51b0
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.43+df3654b3b0
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.4+c5fc38b3b0
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.5+97f703dab0
			fabric-message-api-v1: Fabric Message API (v1) 6.0.10+109a837cb0
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.12+80f8cf51b0
			fabric-models-v0: Fabric Models (v0) 0.4.11+9386d8a7b0
			fabric-networking-api-v1: Fabric Networking API (v1) 4.0.8+0dca0349b0
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.1.4+c5fc38b3b0
			fabric-particles-v1: Fabric Particles (v1) 4.0.0+c5fc38b3b0
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.3+c5fc38b3b0
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.0.16+ad474493b0
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.12+97f703dab0
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.12+80f8cf51b0
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.61+df3654b3b0
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.46+73761d2eb0
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.3+2c869dedb0
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.64+df3654b3b0
			fabric-rendering-v1: Fabric Rendering (v1) 4.2.4+b21c00cbb0
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.1.0+83154f1bb0
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.1.0+c0e5481fb0
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.21+7b70ea8ab0
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.73+8c7b71c2b0
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.21+c5fc38b3b0
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.6+c5fc38b3b0
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.0.10+74e2f560b0
		fabricloader: Fabric Loader 0.15.11
			mixinextras: MixinExtras 0.3.5
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.20.6
		polytone: Polytone 1.20.6-1.18.8
			net_objecthunter_exp4j: exp4j 0.4.8
	Launched Version: 1.20.6
	Launcher name: PrismLauncher
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Intel(R) Iris(R) Plus Graphics GL version 3.2.0 - Build 27.20.100.8783, Intel
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, polytone, file/NewDefault+v1.74[MC1.20-1.20.4].zip (incompatible)
	Current Language: en_us
	Locale: en_DK
	CPU: 8x Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['robotkoer'/50, l='ServerLevel[New World]', x=-25.50, y=97.00, z=-85.50]]
	Active Data Packs: vanilla, fabric, fabric-convention-tags-v2
	Available Data Packs: bundle, fabric, fabric-convention-tags-v2, trade_rebalance, update_1_21, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: -8694392029372688359
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Madis\AppData\Roaming\PrismLauncher\instances\1.20.6(1)\.minecraft\crash-reports\crash-2024-05-19_18.27.34-client.txt
WARN StatusConsoleListener Unable to register Log4j shutdown hook because JVM is shutting down. Using SimpleLogger
```

**Comment by MehVahdJukaar** [comment]
did that happen outside of a world?

**Comment by Madis0** [comment]
It happens as soon as you join a world.

**Comment by MehVahdJukaar** [comment]
does this hapen with the newest version?
