### ISSUE TITLE
Mixin Error 1.21

### ISSUE THREAD

**Issue by T4ge** [MehVahdJukaar/polytone#60]
Tested with NeoForge, 21.0.4, 21.0.30 & 21.0.42
Identical results from all, no other mods installed & fresh instance. 
<details>
  <summary>Log</summary>

  ```
[12:51:18] [main/INFO]: ModLauncher running: args [--username, *, --version, neoforge-21.0.42-beta, --gameDir, E:\Minecraft Install\Instances\Polytone, --assetsDir, E:\Minecraft Install\Install\assets, --assetIndex, 17, --uuid, 7dd988d38cb64d38b6dd4b425fa271d4, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, Yzk2ZmMyYTAtNzFiNS00ZmRhLWE1ZDItZDVjMTVhNDE0MWQy, --xuid, 2535473591704035, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, E:\Minecraft Install\Install\quickPlay\java\1719744676778.json, --fml.neoForgeVersion, 21.0.42-beta, --fml.fmlVersion, 4.0.6, --fml.mcVersion, 1.21, --fml.neoFormVersion, 20240613.152323, --launchTarget, forgeclient]
[12:51:18] [main/INFO]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 21.0.3+9-LTS
[12:51:18] [main/INFO]: ModLauncher 11.0.3+main.0f24dec3 starting: java version 21.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[12:51:18] [main/WARN]: Configuration file E:\Minecraft Install\Instances\Polytone\config\fml.toml is not correct. Correcting
[12:51:18] [main/INFO]: Incorrect key [disableConfigWatcher] was corrected from null to false
[12:51:18] [main/INFO]: Incorrect key [earlyWindowSkipGLVersions] was corrected from null to []
[12:51:18] [main/INFO]: Incorrect key [earlyWindowSquir] was corrected from null to false
[12:51:18] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[12:51:18] [main/INFO]: Trying GL version 4.6
[12:51:18] [main/INFO]: Requested GL version 4.6 got version 4.6
[12:51:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/Minecraft%20Install/Install/libraries/net/fabricmc/sponge-mixin/0.13.4+mixin.0.8.5/sponge-mixin-0.13.4+mixin.0.8.5.jar%23135!/ Service=ModLauncher Env=CLIENT
[12:51:18] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce RTX 3090/PCIe/SSE2 GL version 4.6.0 NVIDIA 555.85, NVIDIA Corporation
[12:51:18] [main/INFO]: Found mod file "client-1.21-20240613.152323-srg.jar" [locator: production client provider +net.neoforged:neoforge:21.0.42-beta:client]
[12:51:18] [main/INFO]: Found mod file "neoforge-21.0.42-beta-universal.jar" [locator: PathBasedLocator[name=neoforge, paths=[E:\Minecraft Install\Install\libraries\net\neoforged\neoforge\21.0.42-beta\neoforge-21.0.42-beta-universal.jar]], reader: mod manifest]
[12:51:18] [main/INFO]: Found mod file "polytone-1.21-2.1.0.jar" [locator: {mods folder locator at E:\Minecraft Install\Instances\Polytone\mods}, reader: mod manifest]
[12:51:19] [main/INFO]: Found 2 dependencies adding them to mods collection
[12:51:19] [main/INFO]: Found library file "exp4j-0.4.8.jar" [parent: polytone-1.21-2.1.0.jar, locator: jarinjar]
[12:51:19] [main/INFO]: Found gamelibrary file "mixinextras-neoforge-0.3.5.jar" [parent: neoforge-21.0.42-beta-universal.jar, locator: jarinjar, reader: mod manifest]
[12:51:19] [main/INFO]: Loading coremod script-engine for [polytone, neoforge]
[12:51:19] [main/INFO]: Compatibility level set to JAVA_21
[12:51:19] [main/INFO]: Launching target 'forgeclient' with arguments [--version, neoforge-21.0.42-beta, --gameDir, E:\Minecraft Install\Instances\Polytone, --assetsDir, E:\Minecraft Install\Install\assets, --uuid, 7dd988d38cb64d38b6dd4b425fa271d4, --username, ****, --assetIndex, 17, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, Yzk2ZmMyYTAtNzFiNS00ZmRhLWE1ZDItZDVjMTVhNDE0MWQy, --xuid, 2535473591704035, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, E:\Minecraft Install\Install\quickPlay\java\1719744676778.json]
[12:51:20] [main/WARN]: Error loading class: top/theillusivec4/curios/client/gui/CuriosScreen (java.lang.ClassNotFoundException: top.theillusivec4.curios.client.gui.CuriosScreen)
[12:51:20] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[12:51:20] [main/FATAL]: Mixin apply for mod polytone failed polytone.mixins.json:GuiGraphicsMixin from mod polytone -> net.minecraft.client.gui.GuiGraphics: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on polytone$modifyBlit could not find any targets matching 'Lnet/minecraft/client/gui/GuiGraphics;m_294769_(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIII)V' in net.minecraft.client.gui.GuiGraphics. Using refmap polytone-common-refmap.json [PREINJECT Applicator Phase -> polytone.mixins.json:GuiGraphicsMixin from mod polytone -> Prepare Injections ->  -> handler$zza000$polytone$modifyBlit(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on polytone$modifyBlit could not find any targets matching 'Lnet/minecraft/client/gui/GuiGraphics;m_294769_(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIII)V' in net.minecraft.client.gui.GuiGraphics. Using refmap polytone-common-refmap.json [PREINJECT Applicator Phase -> polytone.mixins.json:GuiGraphicsMixin from mod polytone -> Prepare Injections ->  -> handler$zza000$polytone$modifyBlit(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.13.4+mixin.0.8.5.jar:0.13.4+mixin.0.8.5]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-11.0.3.jar:11.0.3+main.0f24dec3]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.3.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.3.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.3.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) [securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) [securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) [securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) [?:?]
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) [?:?]
	at java.base/java.lang.Class.getMethods(Class.java:2185) [?:?]
	at MC-BOOTSTRAP/fml_earlydisplay@4.0.6/net.neoforged.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:603) [earlydisplay-4.0.6.jar%23134!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:94) [loader-4.0.6.jar%23110!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:160) [loader-4.0.6.jar%23110!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.6/net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115) [loader-4.0.6.jar%23110!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.3.jar%2399!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.3.jar%2399!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.3.jar%2399!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.3.jar%2399!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.3.jar%2399!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.3.jar%2399!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.3.jar%2399!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]

  ```

**Comment by MehVahdJukaar** [comment]
does this happen with newest neoforge?

**Comment by T4ge** [comment]
Seems to be still happening with NeoForge 21.0.115 using Polytone 2.1.3
<details>
  <summary>Log</summary>

  ```
  [16:55:26] [main/INFO]: ModLauncher running: args [--username, XXXX, --version, neoforge-21.0.115-beta, --gameDir, E:\Minecraft Install\Instances\Poly, --assetsDir, E:\Minecraft Install\Install\assets, --assetIndex, 17, --uuid, 7dd988d38cb64d38b6dd4b425fa271d4, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, Yzk2ZmMyYTAtNzFiNS00ZmRhLWE1ZDItZDVjMTVhNDE0MWQy, --xuid, 2535473591704035, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, E:\Minecraft Install\Install\quickPlay\java\1721746525034.json, --fml.neoForgeVersion, 21.0.115-beta, --fml.fmlVersion, 4.0.18, --fml.mcVersion, 1.21, --fml.neoFormVersion, 20240613.152323, --launchTarget, forgeclient]
[16:55:26] [main/INFO]: JVM identified as Microsoft OpenJDK 64-Bit Server VM 21.0.3+9-LTS
[16:55:26] [main/INFO]: ModLauncher 11.0.4+main.d2e20e43 starting: java version 21.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0
[16:55:26] [main/WARN]: Configuration file E:\Minecraft Install\Instances\Poly\config\fml.toml is not correct. Correcting
[16:55:26] [main/INFO]: Incorrect key [disableConfigWatcher] was corrected from null to false
[16:55:26] [main/INFO]: Incorrect key [earlyWindowSkipGLVersions] was corrected from null to []
[16:55:26] [main/INFO]: Incorrect key [earlyWindowSquir] was corrected from null to false
[16:55:26] [main/INFO]: Loading ImmediateWindowProvider fmlearlywindow
[16:55:26] [main/INFO]: Trying GL version 4.6
[16:55:26] [main/INFO]: Requested GL version 4.6 got version 4.6
[16:55:26] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.6 Source=union:/E:/Minecraft%20Install/Install/libraries/net/fabricmc/sponge-mixin/0.14.0+mixin.0.8.6/sponge-mixin-0.14.0+mixin.0.8.6.jar%23126!/ Service=ModLauncher Env=CLIENT
[16:55:27] [pool-2-thread-1/INFO]: GL info: NVIDIA GeForce RTX 3090/PCIe/SSE2 GL version 4.6.0 NVIDIA 555.85, NVIDIA Corporation
[16:55:27] [main/INFO]: Found mod file "client-1.21-20240613.152323-srg.jar" [locator: production client provider +net.neoforged:neoforge:21.0.115-beta:client]
[16:55:27] [main/INFO]: Found mod file "neoforge-21.0.115-beta-universal.jar" [locator: PathBasedLocator[name=neoforge, paths=[E:\Minecraft Install\Install\libraries\net\neoforged\neoforge\21.0.115-beta\neoforge-21.0.115-beta-universal.jar]], reader: mod manifest]
[16:55:27] [main/INFO]: Found mod file "polytone-1.21-2.1.3.jar" [locator: {mods folder locator at E:\Minecraft Install\Instances\Poly\mods}, reader: mod manifest]
[16:55:27] [main/INFO]: Found 2 dependencies adding them to mods collection
[16:55:27] [main/INFO]: Found library file "exp4j-0.4.8.jar" [parent: polytone-1.21-2.1.3.jar, locator: jarinjar]
[16:55:27] [main/INFO]: Found gamelibrary file "mixinextras-neoforge-0.3.5.jar" [parent: neoforge-21.0.115-beta-universal.jar, locator: jarinjar, reader: mod manifest]
[16:55:27] [main/INFO]: Loading coremod script-engine for [neoforge]
[16:55:28] [main/INFO]: Compatibility level set to JAVA_21
[16:55:28] [main/INFO]: Launching target 'forgeclient' with arguments [--version, neoforge-21.0.115-beta, --gameDir, E:\Minecraft Install\Instances\Poly, --assetsDir, E:\Minecraft Install\Install\assets, --uuid, 7dd988d38cb64d38b6dd4b425fa271d4, --username, XXXX, --assetIndex, 17, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, Yzk2ZmMyYTAtNzFiNS00ZmRhLWE1ZDItZDVjMTVhNDE0MWQy, --xuid, 2535473591704035, --userType, msa, --versionType, release, --width, 1024, --height, 768, --quickPlayPath, E:\Minecraft Install\Install\quickPlay\java\1721746525034.json]
[16:55:28] [main/WARN]: Error loading class: top/theillusivec4/curios/client/gui/CuriosScreen (java.lang.ClassNotFoundException: top.theillusivec4.curios.client.gui.CuriosScreen)
[16:55:28] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[16:55:28] [main/FATAL]: Mixin apply for mod polytone failed polytone.mixins.json:GuiGraphicsMixin from mod polytone -> net.minecraft.client.gui.GuiGraphics: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on polytone$modifyBlit could not find any targets matching 'Lnet/minecraft/client/gui/GuiGraphics;m_294769_(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIII)V' in net/minecraft/client/gui/GuiGraphics. Using refmap polytone-common-refmap.json [PREINJECT Applicator Phase -> polytone.mixins.json:GuiGraphicsMixin from mod polytone -> Prepare Injections -> handler$zza000$polytone$modifyBlit(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on polytone$modifyBlit could not find any targets matching 'Lnet/minecraft/client/gui/GuiGraphics;m_294769_(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIII)V' in net/minecraft/client/gui/GuiGraphics. Using refmap polytone-common-refmap.json [PREINJECT Applicator Phase -> polytone.mixins.json:GuiGraphicsMixin from mod polytone -> Prepare Injections -> handler$zza000$polytone$modifyBlit(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse ->  -> Validate Targets]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.selectors.TargetSelectors.validate(TargetSelectors.java:346) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:315) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:288) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:279) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:145) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:592) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1395) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:696) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:288) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:220) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.14.0+mixin.0.8.6.jar:0.14.0+mixin.0.8.6]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-11.0.4.jar:11.0.4+main.d2e20e43]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:94) ~[modlauncher-11.0.4.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-11.0.4.jar:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:57) ~[modlauncher-11.0.4.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:190) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:298) ~[securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:311) [securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:298) [securejarhandler-3.0.8.jar:?]
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:214) [securejarhandler-3.0.8.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3578) [?:?]
	at java.base/java.lang.Class.privateGetPublicMethods(Class.java:3603) [?:?]
	at java.base/java.lang.Class.getMethods(Class.java:2185) [?:?]
	at MC-BOOTSTRAP/fml_earlydisplay@4.0.18/net.neoforged.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:605) [earlydisplay-4.0.18.jar%23106!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:94) [loader-4.0.18.jar%23105!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:160) [loader-4.0.18.jar%23105!/:4.0]
	at MC-BOOTSTRAP/fml_loader@4.0.18/net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115) [loader-4.0.18.jar%23105!/:4.0]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23102!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23102!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23102!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23102!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23102!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23102!/:?]
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23102!/:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]

  ```

**Comment by MehVahdJukaar** [comment]
I have no idea. I was able to run it in Dev fine. It's always mixing not working in the weirdest cases

**Comment by T4ge** [comment]
Closing this issue as it's now working after a few updates
