### ISSUE TITLE
Mixin Error NeoForge 1.20.4

### ISSUE THREAD

**Issue by Mat1212fr** [MehVahdJukaar/polytone#89]
Hi,
As mentionned in #60 (but in 1.20.4) I got this issue on NeoForge 20.4.237. Since it's a bug I'm posting it here, while I will disable Polytone.

```
[00:21:07] [main/FATAL]: Mixin apply for mod polytone failed polytone.mixins.json:GuiGraphicsMixin from mod polytone -> net.minecraft.client.gui.GuiGraphics: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on polytone$modifyBlit could not find any targets matching 'Lnet/minecraft/client/gui/GuiGraphics;m_294769_(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIII)V' in net.minecraft.client.gui.GuiGraphics. Using refmap polytone-common-refmap.json [PREINJECT Applicator Phase -> polytone.mixins.json:GuiGraphicsMixin from mod polytone -> Prepare Injections ->  -> handler$bdd000$polytone$modifyBlit(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on polytone$modifyBlit could not find any targets matching 'Lnet/minecraft/client/gui/GuiGraphics;m_294769_(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIII)V' in net.minecraft.client.gui.GuiGraphics. Using refmap polytone-common-refmap.json [PREINJECT Applicator Phase -> polytone.mixins.json:GuiGraphicsMixin from mod polytone -> Prepare Injections ->  -> handler$bdd000$polytone$modifyBlit(Lnet/minecraft/client/renderer/texture/TextureAtlasSprite;IIIIILorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[sponge-mixin-0.13.1+mixin.0.8.5.jar:0.13.1+mixin.0.8.5]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:169) ~[securejarhandler-2.1.24.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$20(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:288) ~[securejarhandler-2.1.24.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:275) ~[securejarhandler-2.1.24.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:191) ~[securejarhandler-2.1.24.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:?]
	at java.lang.Class.getMethods(Unknown Source) ~[?:?]
	at net.neoforged.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:594) ~[earlydisplay-2.0.17.jar:2.0]
	at net.neoforged.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:85) ~[loader-2.0.17.jar:2.0]
	at net.neoforged.fml.loading.FMLLoader.beforeStart(FMLLoader.java:206) ~[loader-2.0.17.jar:2.0]
	at net.neoforged.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:115) ~[loader-2.0.17.jar:2.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```

**Comment by MehVahdJukaar** [comment]
this likely occurred due to a recent update of neoforge. unfortunatellly i dont plan on updating that intermediate little version anymore. only supported versions now are 1.20.1 and 1.21
